### ISSUE TITLE
"File is not an EXS file"

### ISSUE THREAD

**Issue by daslicht** [AudioKit/SamplerDemo#7]
```
% python3 exs2sfz.py CrushLead1.exs CrushLead1.sfz 
Traceback (most recent call last):
  File "exs2sfz.py", line 609, in <module>
    exs = EXSInstrument(sys.argv[1], samplefolder)
  File "exs2sfz.py", line 356, in __init__
    raise RuntimeError("File is not an EXS file; will not parse!")
RuntimeError: File is not an EXS file; will not parse!
ansolas@Marcs-Mac-mini crushlead1 % 
```

**Comment by getdunne** [comment]
I didn’t write that script, and as you see it’s undocumented, so I can’t maintain it.

-shane
________________________________
From: Marc Wensauer ***@***.***>
Sent: Wednesday, June 16, 2021 8:07:40 AM
To: AudioKit/SamplerDemo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AudioKit/SamplerDemo] "File is not an EXS file" (#7)


% python3 exs2sfz.py CrushLead1.exs CrushLead1.sfz
Traceback (most recent call last):
  File "exs2sfz.py", line 609, in <module>
    exs = EXSInstrument(sys.argv[1], samplefolder)
  File "exs2sfz.py", line 356, in __init__
    raise RuntimeError("File is not an EXS file; will not parse!")
RuntimeError: File is not an EXS file; will not parse!
ansolas@Marcs-Mac-mini crushlead1 %

**Comment by daslicht** [comment]
I see thanks for the reply !

**Comment by getdunne** [comment]
@daslicht I think the script was written for an older version of ESX24, so it often fails on newer files. See this video for the basis of a MUCH better approach for converting ESX24/Sampler maps: https://youtu.be/zoI72uGVPzQ?t=180

**Comment by PaulBatchelor** [comment]
Here's where the error is coming from: https://github.com/AudioKit/SamplerDemo/blob/97489f57adec72043f4548baadaf73968a9948a8/Sounds/exs2sfz.py#L356

It's failing the initial header checks.

I downloaded the CrushLead1.exs and opened it in a hex editor. Without actually testing anything, it looks like the it has the magic 'TBOS' constant in the right place, but the header type signature is wrong (it is expecting 0x00000101, but the exs file has it as 0x04000101). No idea what this means though.

**Comment by daslicht** [comment]
> @daslicht I think the script was written for an older version of ESX24, so it often fails on newer files. See this video for the basis of a MUCH better approach for converting ESX24/Sampler maps: https://youtu.be/zoI72uGVPzQ?t=180

Unfortunately Logic no longer contains teh EXS24, it was replaced by "Sampler" which no loger gas this mapping viw where you coudl copy paste stuff as text
